DatabaseSettings:
    CommandTimeout: 30000

ConnectionStrings:
    ControlDb: 'Host=${ControlDb.Host};Port=${ControlDb.Port};Database=control_db;Username=${ControlDb.User};Password=${ControlDb.Password}'
    UserDb: 'Host=${UserDb.Host};Port=${UserDb.Port};Database=user_db;Username=${UserDb.User};Password=${UserDb.Password}'

KeycloakSettings:
    Authority: '${Keycloak.Host}/realms/aid-kit-realm'
    MetadataAddress: '${Keycloak.Host}/realms/aid-kit-realm/.well-known/openid-configuration'
    IsRequireHttpsMetadata: false
    IsValidateIssuer: false
    ValidIssuers:
        - '${Keycloak.Host}/realms/aid-kit-realm'
    IsValidateAudience: true